import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Read config
SENDER_EMAIL = os.getenv("EMAIL_USER")
APP_PASSWORD = os.getenv("EMAIL_PASS")
EMAIL_TO_RAW = os.getenv("EMAIL_TO")


# Validate config
if not all([SENDER_EMAIL, APP_PASSWORD, EMAIL_TO_RAW]):
    raise Exception("❌ Missing email config in .env file")


# Convert to list (single or multiple)
RECEIVER_EMAILS = [
    e.strip() for e in EMAIL_TO_RAW.split(",") if e.strip()
]


def send_alert(patient_id, risk, hr, bp):
    """
    Send critical alert email for one patient
    """

    subject = "🚨 ICU CRITICAL ALERT (AI Detected)"

    body = f"""
ICU AI ALERT SYSTEM 🚨

A patient is in CRITICAL condition.

Patient ID: {patient_id}
Risk Score: {risk:.2f}%

Heart Rate: {hr}
BP Mean: {bp}

Immediate medical attention required.

---------------------------------
Generated by AI Monitoring System
"""

    # Create email
    msg = MIMEMultipart()
    msg["From"] = SENDER_EMAIL
    msg["To"] = ", ".join(RECEIVER_EMAILS)
    msg["Subject"] = subject

    msg.attach(MIMEText(body, "plain"))

    try:
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()

        server.login(SENDER_EMAIL, APP_PASSWORD)

        server.sendmail(
            SENDER_EMAIL,
            RECEIVER_EMAILS,
            msg.as_string()
        )

        server.quit()

        print(f"✅ Alert email sent for Patient {patient_id}")

    except Exception as e:
        print("❌ Email sending failed:", e)
